### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by xhochy** [pwaller/pyprof2calltree#20]
Looking at the `setup.py` the classifiers state that this package is licensed under the BSD license, the code https://github.com/pwaller/pyprof2calltree/blob/master/pyprof2calltree.py#L13 actually contains an MIT license.

It would be nice, if you could clear this up and add a `LICENSE` file. There is not much difference between MIT and BSD but having a clear license is always better ;)

**Comment by pwaller** [comment]
Hi @xhochy: Please take a look at https://github.com/pwaller/pyprof2calltree/commit/512730f5d5f9b8aecdb778bfb15277d400f52849 and let me know if you have any further concerns. I'll make release 1.4.2 on PyPi later today (say, in ~8 hours) so that the license is correctly reflected there, so please take a look and let me know before then if you spot any trouble. I also added you to the thanks section of the CONTRIBUTORS file, I hope you don't mind.

**Comment by xhochy** [comment]
@pwaller Awesome! Thank you for taking care of this so quickly (and for building `pyprof2calltree`, I'm a frequent user).

**Comment by pwaller** [comment]
Excellent. I did not build it, I just do my best to maintain it :)

**Comment by pwaller** [comment]
[It's deployed](https://pypi.python.org/pypi/pyprof2calltree/1.4.2). Thanks again.
