### ISSUE TITLE
Best way to cite `pyprof2calltree`?

### ISSUE THREAD

**Issue by motiwari** [pwaller/pyprof2calltree#60]
Hi, what is the best way to cite `pyprof2calltree`, e.g., when using it in an academic publication?

**Comment by pwaller** [comment]
It's a good question. I am merely a maintainer, having written none-to-very little of the code, but so far as I know this GitHub repository is the canonical place to find this code. You can see contributors listed in https://github.com/pwaller/pyprof2calltree/blob/master/CONTRIBUTORS.txt. I do not hold an opinion on how to cite it. Perhaps 'pyprof2calltree contributors' would be fairest, since I do not know the relative weight of contributions. I suspect the earliest names in the copyright stanza in pyprof2calltree.py are listed in order of most significant contributors, but I do not know the history. I personally don't deserve the credit for their efforts, but many people have contributed a little.

For my own interest I'm curious to see how you choose to cite pyprof2calltree and would love to hear where we're being cited! Closing for now but please feel free to reopen if there is a thread to be addressed on my side here.
